### ISSUE TITLE
Campfire broken

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#656]
Becomes broken when a pawn tries to relax socially on an unfuelled campfire, the campfire magically ignites  making light appear, as if the pawn had refuelled it, but it hasn't been refuelled, and subsequencly when a pawn tries to refuel it, they can't and displays this error. 
Possible important note no matter what material they try to refuel it with they only ever carry 1 unit of it.

I can reconstruct it and it'll be fine but it can be devastating in some circumstances early game e.g. cold / raw food mood swings etc.

![campfire](https://cloud.githubusercontent.com/assets/5264667/22268740/8965c26c-e280-11e6-974f-39dc687ededf.jpg)

**Comment by Rhyssia** [comment]
please select "Invalid count. 0, setting to 1. Job was.RefuelBurner A=Thing_Kindling######## B=Thing_Campfire########"

There will show additional text at bottom. Please Screen shot that text.

**Comment by zakhad** [comment]
![campfire2](https://cloud.githubusercontent.com/assets/5264667/22276715/76f84348-e2ad-11e6-8c09-0c492f5c03e6.jpg)

**Comment by zakhad** [comment]
![campfire2](https://cloud.githubusercontent.com/assets/5264667/22276787/098cd20a-e2ae-11e6-9a32-e0d7a69a5484.jpg)

**Comment by skyarkhangel** [comment]
ahh yes. known problem :)

**Comment by zakhad** [comment]
Resolved.

**Comment by zoranjoza** [comment]
it is not resolved. still getting error. downloaded modpack from here two days ago.

```
Invalid count: 0, setting to 1. Job was RefuelBurner A=Thing_Kindling553691 B=Thing_Campfire931092
Verse.Log:Error(String)
Verse.AI.Toils_Haul:ErrorCheckForCarry(Pawn, Thing)
Verse.AI.<StartCarryThing>c__AnonStorey41A:<>m__67B()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:Notify_PatherArrived()
Verse.AI.Pawn_PathFollower:PatherArrived()
Verse.AI.Pawn_PathFollower:TryEnterNextPathCell()
Verse.AI.Pawn_PathFollower:PatherTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
```

`Could not deposit hauled thing in container: Campfire931092
Verse.Log:Warning(String)
SK.<>c__DisplayClass6_0:<DepositFuelIntoBurner>b__0()
Verse.AI.JobDriver:TryActuallyStartNextToil()
Verse.AI.JobDriver:ReadyForNextToil()
Verse.AI.JobDriver:DriverTick()
Verse.AI.Pawn_JobTracker:JobTrackerTick()
Verse.Pawn:Tick()
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:Update()
Verse.Root_Play:Update()
`
